export const links = {
    QUALSU: "https://qualsu.ru",
    FEEDBACK: "https://feedback.qualsu.ru",
    QUAL_ID: "https://id.qualsu.ru",
    STATUS: "https://status.qualsu.ru",
    NOTTER: "https://notter.su",
    TODO_NOTTER: "https://todo.notter.su",
    INSDL: "https://github.com/qualsu/insdl",
    INAPI: "https://github.com/qualsu/inapi",
    SHRTL: "https://shrtl.ru",
    GITHUB_QUALSU: "https://github.com/qualsu",
    TELEGRAM_QUALSU: "https://t.me/qualsu",
    KENYCLOUD: "https://github.com/qualsu/kenycloud",
    CODE_NOTTER: "https://code.notter.su",
    VOICY_DISCORD: "https://discord.com/invite/4ed6dbJZvZ",
    OMI: "https://omilang.fun",
    QUALCLOUD: "https://cloud.qualsu.ru",
    QUALAI: "https://ai.qualsu.ru",
    QAI: "https://qai.qualsu.ru",
    BGDPS: "https://github.com/BetterGDPS/DemonList/"
}